paper: switch to IEEE template, hack on intro, move future work
Signed-off-by: Michael Sevilla <mikesevilla3@gmail.com>

diff --git a/paper/build b/paper/build
--- a/paper/build
+++ b/paper/build
@@ -1,38 +1,29 @@
 #!/bin/bash
+
+rm -r _minted-paper paper.aux paper.bbl paper.blg paper.log paper.out paper.synctex.gz build.log >> /dev/null 2>&1
 set -x
-mkdir -p out
+cp biblio/references.bib paper.bib
 
-cp biblio/references.bib references.bib
-
+# Build the paper
 docker run --rm \
-  --workdir='/root/' \
-  -v `pwd`/paper.tex:/root/paper.tex \
-  -v `pwd`/references.bib:/root/references.bib \
-  -v `pwd`/sections:/root/sections \
-  -v `pwd`/figures:/root/figures \
-  -v `pwd`/.deps/acmart.cls:/root/acmart.cls \
-  -v `pwd`/.deps/ACM-Reference-Format.bst:/root/ACM-Reference-Format.bst \
-  -v `pwd`/out:/root/out \
+  --name latex \
   --entrypoint=/bin/bash \
+  -v `pwd`/:/mnt \
   michaelsevilla/texlive:latest -c \
-    "pdflatex -shell-escape paper;
-     bibtex paper;
-     pdflatex -shell-escape paper;
-     pdflatex -shell-escape paper;
-     mv paper.pdf /root/out/" &> build.log
-  #--entrypoint=/bin/bash -it michaelsevilla/texlive:latest
-    
-  #tianon/latex sh -c \
+    "cd /mnt ; \
+     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper; \
+     bibtex paper; \
+     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper; \
+     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper;" &> build.log
 
-if [ $? != "0" ] ; then
-  echo "ERROR"
+ERR=$?
+if [ $ERR != "0" ] ; then
+  echo "ERROR: $ERR"
   cat build.log
-  rm build.log
-  exit 1
 fi
 
-mv out/paper.pdf .
-rm -r out
-rm build.log
+set +e
+rm -r _minted-paper paper.aux paper.bbl paper.blg paper.log paper.out paper.synctex.gz build.log >> /dev/null 2>&1
 
-exit 0
+echo "SUCCESS"
+
